=== OFAI/PunCAT/src/main/resources/puns/puncat.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT corpus (instance+)>
<!ATTLIST corpus lang CDATA #REQUIRED>
<!ATTLIST corpus id ID #REQUIRED>

<!ELEMENT instance (img?,text)>
<!ATTLIST instance id ID #REQUIRED>

<!ELEMENT img (keyword*)>
<!ATTLIST img src CDATA #REQUIRED>

<!ELEMENT keyword (#PCDATA)>

<!ELEMENT text (#PCDATA|pun)*>

<!ELEMENT pun (#PCDATA)>
<!ATTLIST pun first_lemma CDATA #REQUIRED>
<!ATTLIST pun second_lemma CDATA #REQUIRED>
<!ATTLIST pun first_sense CDATA #REQUIRED>
<!ATTLIST pun second_sense CDATA #REQUIRED>

=== OFAI/PunCAT/src/main/resources/puns/puns123.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE corpus SYSTEM 'puncat.dtd'>
<corpus lang="en" id="puncat-123">
  <instance id="p1">
    <img src="alice.png">
    </img>
    <text>
      ‘That’s the reason they’re called <pun
      first_lemma="lesson" first_sense="lesson%1:04:01::"
      second_lemma="lessen" second_sense="lessen%2:30:00::">lessons</pun>,’ the Gryphon remarked: ‘because they lessen from day to day.’
  </text>
  </instance>
  <instance id="p2">
    <text>
      When they operated on him she prepared him for the operating table; and they had a joke about friend or <pun
      first_lemma="enema" first_sense="enema%1:04:00::"
      second_lemma="enemy" second_sense="enemy%1:18:00::">enema</pun>.
    </text>
  </instance>
    <instance id="p3">
    <img src="cloudy.gif">
    </img>
    <text>
      Hold on, everyone. This ain't gonna be no <pun
      first_lemma="picnic" first_sense="picnic%1:04:00::"
      second_lemma="picnic" second_sense="picnic%1:13:00::">picnic</pun>.
    </text>
  </instance>
</corpus>

=== OFAI/PunCAT/src/main/resources/puns/puns456.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE corpus SYSTEM 'puncat.dtd'>
<corpus lang="en" id="puncat-456">
  <instance id="p4">
    <img src="nemo.gif">
    </img>
    <text>
      I know what that is. Sandy Plankton saw one. He said it was called... a <pun
      first_lemma="butt" first_sense="butt%1:08:00::"
      second_lemma="boat" second_sense="boat%1:06:00::">butt</pun>!
  </text>
  </instance>
  <instance id="p5">
    <text>
      “Got a <pun
      first_lemma="club" first_sense="club%1:06:04::"
      second_lemma="club" second_sense="club%1:06:00::">club</pun>,” said Lias proudly. “Got a nail in it.”
    </text>
  </instance>
    <instance id="p6">
    <img src="animalcrackers.gif">
    </img>
    <text>
      I was using the subjunctive instead of the past tense. Yes, we're a way past <pun
      first_lemma="tense" first_sense="tense%1:10:00::"
      second_lemma="tent" second_sense="tent%1:06:00::">tense</pun>; we're living in bungalows now.
    </text>
  </instance>
</corpus>
